name: Feature request
description: Suggest an improvement for this library project
title: "feat: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea.
        Please describe the use case and expected API.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
